wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: Graph Attention Convolutional Network - 2 layers
dataset:
  desc: null
  value: MUTAG
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: "SGD (\nParameter Group 0\n    dampening: 0\n    differentiable: False\n\
    \    foreach: None\n    lr: 0.01\n    maximize: False\n    momentum: 0\n    nesterov:\
    \ False\n    weight_decay: 0\n)"
shuffle:
  desc: null
  value: true
activation:
  desc: null
  value: LeakyReLU(negative_slope=0.01)
pooling:
  desc: null
  value: MeanPool()
aggregation:
  desc: null
  value: MeanAggregation()
dropout:
  desc: null
  value: 0.0
weight_decay:
  desc: null
  value: 1.0e-06
pos_weight:
  desc: null
  value: 0.7
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698227725.777597
    t:
      1:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: darwin-x86_64
