wandb_version: 1

experiment_group:
  desc: null
  value: GraphConv with GraphSumEdgeConv edge layer.
learning_rate:
  desc: null
  value: 0.1
architecture:
  desc: null
  value: GNN with 2 layers and 5025 trainable parameters.
dataset:
  desc: null
  value: MUTAG
epochs:
  desc: null
  value: 150
batch_size:
  desc: null
  value: 64
optimizer:
  desc: null
  value: "SGD (\nParameter Group 0\n    dampening: 0\n    differentiable: False\n\
    \    foreach: None\n    lr: 0.1\n    maximize: False\n    momentum: 0\n    nesterov:\
    \ False\n    weight_decay: 0.001\n)"
pooling:
  desc: null
  value: MaxPool
dropout:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.001
pos_weight:
  desc: null
  value: '0.47191012'
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698495059.783371
    t:
      1:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 1
      - 5
      13: darwin-x86_64
